"""
MaxHealth — Universal Device Extractor (auto.py)
=================================================
Processes any CSV export using a saved device mapping config (JSON).
Mapping configs are generated by the MaxHealth HTML tracker (Import > Add New Device)
and saved to the mappings/ folder.

Usage:
    python auto.py --config mappings/mydevice.json --input inbox/export.csv
    python auto.py --config mappings/mydevice.json --input inbox/export.csv --dry-run

Priority rule: manually logged nutrition always wins.
Device data fills in wearable fields only if not already present in combined.csv.
"""

import csv
import json
import os
import sys
import argparse
import logging
from datetime import datetime, timedelta

# ── Column name constants (MaxHealth schema) ─────────────────────────────────
SCHEMA_FIELDS = [
    'date',
    'weight_kg',
    'steps',
    'calories_out',
    'total_sleep_min',
    'deep_min',
    'rem_min',
    'light_min',
    'hrv_rmssd',
    'spo2_avg',
    'heart_rate',
    'fat_pct',
    'calories_in',
    'protein_g',
    'carbs_g',
]

# ── Unit conversion handlers ──────────────────────────────────────────────────
def apply_conversion(value, conversion):
    """Apply a unit conversion to a raw string value. Returns float or None."""
    if value is None or str(value).strip() == '':
        return None
    try:
        v = float(str(value).strip())
    except ValueError:
        return None

    c = (conversion or 'none').strip().lower()
    if c == 'none' or c == '':
        return v
    elif c == 'multiply_60':
        return v * 60        # hours → minutes
    elif c == 'divide_60':
        return v / 60        # minutes → hours (rarely needed)
    elif c == 'divide_2.205' or c == 'lbs_to_kg':
        return round(v / 2.205, 2)   # lbs → kg
    elif c == 'multiply_2.205' or c == 'kg_to_lbs':
        return round(v * 2.205, 2)
    elif c.startswith('multiply_'):
        factor = float(c.replace('multiply_', ''))
        return v * factor
    elif c.startswith('divide_'):
        factor = float(c.replace('divide_', ''))
        return v / factor if factor != 0 else None
    else:
        logging.warning(f"Unknown conversion '{conversion}' — using raw value")
        return v


# ── Date normalisation ────────────────────────────────────────────────────────
def parse_date(raw, date_format):
    """Parse a date string into YYYY-MM-DD. Returns None on failure."""
    raw = raw.strip()
    formats_to_try = []

    if date_format:
        # Convert user-friendly format to strptime format
        fmt = date_format.strip()
        fmt = fmt.replace('YYYY', '%Y').replace('MM', '%m').replace('DD', '%d')
        formats_to_try.append(fmt)

    # Always try these as fallbacks
    formats_to_try += [
        '%Y-%m-%d', '%d/%m/%Y', '%d/%m/%y',
        '%m/%d/%Y', '%m/%d/%y', '%Y/%m/%d',
        '%d-%m-%Y', '%d-%m-%y', '%Y%m%d',
    ]

    for fmt in formats_to_try:
        try:
            d = datetime.strptime(raw, fmt)
            return d.strftime('%Y-%m-%d')
        except ValueError:
            continue

    return None


# ── Gap detection ─────────────────────────────────────────────────────────────
def detect_gaps(dates_sorted):
    """Return list of (from_date, to_date, gap_days) for gaps > 1 day."""
    gaps = []
    for i in range(1, len(dates_sorted)):
        try:
            prev = datetime.strptime(dates_sorted[i-1], '%Y-%m-%d')
            curr = datetime.strptime(dates_sorted[i], '%Y-%m-%d')
            diff = (curr - prev).days
            if diff > 1:
                gaps.append((dates_sorted[i-1], dates_sorted[i], diff - 1))
        except ValueError:
            continue
    return gaps


# ── Main extractor ────────────────────────────────────────────────────────────
def run(config_path, input_path, output_dir='data/tables', dry_run=False):
    logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

    # Load config
    if not os.path.exists(config_path):
        logging.error(f"Config not found: {config_path}")
        sys.exit(1)

    with open(config_path, 'r', encoding='utf-8') as f:
        config = json.load(f)

    device_name = config.get('device_name', 'unknown_device')
    date_column = config.get('date_column')
    date_format = config.get('date_format', '')
    mappings = config.get('mappings', [])

    logging.info(f"Device: {device_name}")
    logging.info(f"Config: {len(mappings)} field mappings")

    if not date_column:
        logging.error("Config missing 'date_column'")
        sys.exit(1)

    # Load input CSV
    if not os.path.exists(input_path):
        logging.error(f"Input file not found: {input_path}")
        sys.exit(1)

    rows = []
    with open(input_path, 'r', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames or []
        for row in reader:
            rows.append(row)

    logging.info(f"Input: {len(rows)} rows, {len(headers)} columns")

    # Validate date column exists
    if date_column not in headers:
        logging.error(f"Date column '{date_column}' not found in file. Available: {headers}")
        sys.exit(1)

    # Validate mapping columns exist
    for m in mappings:
        if m['source_column'] not in headers:
            logging.warning(f"Mapped column '{m['source_column']}' not found in file — skipping")

    # Process rows
    processed = []
    skipped = 0
    flagged = []

    for i, row in enumerate(rows):
        raw_date = row.get(date_column, '').strip()
        iso_date = parse_date(raw_date, date_format)

        if not iso_date:
            flagged.append(f"Row {i+2}: could not parse date '{raw_date}'")
            skipped += 1
            continue

        out_row = {'date': iso_date}
        for m in mappings:
            src = m.get('source_column')
            tgt = m.get('target_field')
            conv = m.get('unit_conversion', 'none')
            if src not in headers:
                continue
            raw_val = row.get(src, '').strip()
            converted = apply_conversion(raw_val, conv)
            if converted is not None:
                out_row[tgt] = converted

        processed.append(out_row)

    logging.info(f"Processed: {len(processed)} valid rows, {skipped} skipped")

    # Gap detection
    dates_sorted = sorted(r['date'] for r in processed)
    gaps = detect_gaps(dates_sorted)
    if gaps:
        logging.warning(f"{len(gaps)} gap(s) detected in data:")
        for g in gaps:
            logging.warning(f"  {g[0]} → {g[1]}: {g[2]} missing day(s)")
    else:
        logging.info("No gaps detected")

    if flagged:
        logging.warning(f"{len(flagged)} rows flagged:")
        for f in flagged[:10]:
            logging.warning(f"  {f}")
        if len(flagged) > 10:
            logging.warning(f"  …and {len(flagged) - 10} more")

    if dry_run:
        logging.info("DRY RUN — no files written")
        if processed:
            logging.info("Sample output (first 3 rows):")
            for r in processed[:3]:
                logging.info(f"  {r}")
        return

    # Write to output table
    # Device data goes into a device-specific table, then merge.py joins it
    safe_name = device_name.lower().replace(' ', '_').replace('/', '_')
    output_path = os.path.join(output_dir, f'{safe_name}.csv')

    os.makedirs(output_dir, exist_ok=True)

    # Determine all fields present across all rows
    all_fields = ['date']
    for r in processed:
        for k in r:
            if k != 'date' and k not in all_fields:
                all_fields.append(k)

    # Load existing table to merge (priority: existing wins for non-null values)
    existing = {}
    if os.path.exists(output_path):
        with open(output_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                existing[row['date']] = row
        logging.info(f"Existing table: {len(existing)} rows")

    merged = 0
    added = 0
    for r in processed:
        d = r['date']
        if d in existing:
            # Only fill in missing values — never overwrite
            for k, v in r.items():
                if k != 'date' and (not existing[d].get(k) or existing[d][k] == ''):
                    existing[d][k] = v
                    # Add new field to field list if needed
                    if k not in all_fields:
                        all_fields.append(k)
            merged += 1
        else:
            existing[d] = r
            added += 1

    # Sort by date
    sorted_rows = sorted(existing.values(), key=lambda x: x.get('date', ''))

    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=all_fields, extrasaction='ignore')
        writer.writeheader()
        for row in sorted_rows:
            writer.writerow({k: row.get(k, '') for k in all_fields})

    logging.info(f"Written: {output_path} ({len(sorted_rows)} rows total, {added} new, {merged} updated)")
    logging.info(f"UPDATE COMPLETE — {device_name} data ready for merge")


# ── CLI ───────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='MaxHealth Universal Device Extractor',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python auto.py --config mappings/oura.json --input inbox/oura_export.csv
  python auto.py --config mappings/garmin.json --input inbox/garmin.csv --dry-run

Mapping configs are generated by the MaxHealth HTML tracker.
Go to Import > Add New Device, upload a sample CSV, confirm the mapping,
then download and save the JSON to the mappings/ folder.
        """
    )
    parser.add_argument('--config',  required=True, help='Path to device mapping JSON config')
    parser.add_argument('--input',   required=True, help='Path to device CSV export file')
    parser.add_argument('--output',  default='data/tables', help='Output directory (default: data/tables)')
    parser.add_argument('--dry-run', action='store_true', help='Preview without writing files')
    args = parser.parse_args()

    run(args.config, args.input, args.output, args.dry_run)
