"""Persona 49: Trends topic chips - All shows everything, a topic hides the other groups' cards, choice persists, hide/reorder system unaffected, captions present."""
import sys, re, json; sys.path.insert(0, __file__.rsplit('/',1)[0])
from harness import *
from playwright.sync_api import sync_playwright
f = Findings()
with fresh_server() as root, sync_playwright() as pw:
    b = pw.chromium.launch(); errs = []
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, service_workers='block')
    ctx.route(re.compile(r'https://(cdn\.jsdelivr\.net|cdnjs\.cloudflare\.com|fonts\.(googleapis|gstatic)\.com)/.*'), lambda r: r.abort())
    page = ctx.new_page(); page.on('pageerror', lambda e: errs.append(str(e)[:160]))
    page.goto('http://localhost:5757/'); page.wait_for_timeout(1500)
    page.evaluate("switchTabById('trends')"); page.wait_for_timeout(1000)
    chips = page.evaluate("[...document.querySelectorAll('#mhTrendsGroupBar .mh-grp-chip')].map(c=>c.textContent)")
    if chips != ['All', 'Body', 'Heart & sleep', 'Food', 'Patterns']: f.add('BUG', f'chips wrong: {chips}')
    hid = lambda: page.evaluate("[...document.querySelectorAll('.mh-grp-hide')].map(e=>e.id)")
    if hid(): f.add('BUG', f'All hides cards: {hid()}')
    page.evaluate("mhTrendsGroupSet('food')")
    h = hid()
    if 'mcWeight' not in h or 'mcHR' not in h or 'patternsCard' not in h or 'bodyCompCard' not in h: f.add('BUG', f'Food did not hide other groups: {h}')
    if 'mcCal' in h or 'topFoodsCard' in h or 'dayOfWeekCard' in h: f.add('BUG', f'Food hid its own cards: {h}')
    page.evaluate("mhTrendsGroupSet('body')")
    h = hid()
    if 'mcCal' not in h or 'journeyCard' in h or 'bodyCompCard' in h: f.add('BUG', f'Body filter wrong: {h}')
    page.reload(); page.wait_for_timeout(1500); page.evaluate("switchTabById('trends')"); page.wait_for_timeout(800)
    if page.evaluate("document.querySelector('#mhTrendsGroupBar .mh-grp-chip.active')?.textContent") != 'Body': f.add('BUG', 'topic choice not remembered')
    page.evaluate("mhTrendsGroupSet('all')")
    if hid(): f.add('BUG', 'All did not restore')
    caps = page.evaluate("document.querySelectorAll('.mh-qline').length")
    if caps < 4: f.add('BUG', f'captions missing: {caps}')
    # daily (Today) view: merged sections + chips apply there too
    csvd = "date,weight,fat_pct,muscle_pct,bone_mass_kg,hydration_kg,sleep_duration,sleep_deep,sleep_efficiency,bedtime,steps\n" + page.evaluate("(()=>{const d=new Date();const z=n=>String(n).padStart(2,'0');const iso=d.getFullYear()+'-'+z(d.getMonth()+1)+'-'+z(d.getDate());return iso+',92.2,20.2,75.8,3.7,50.1,420,80,88,23:10,8000'})()") + "\n"
    page.evaluate("(t)=>localStorage.setItem('mh_combined_csv_cache',t)", csvd)
    page.reload(); page.wait_for_timeout(1500); page.evaluate("switchTabById('trends')"); page.wait_for_timeout(800)
    page.evaluate("setTrendsFilter('today', document.getElementById('trendsBtnToday'))"); page.wait_for_timeout(1200)
    titles = page.evaluate("[...document.querySelectorAll('#trendsDailyView [id^=title-dv-]')].map(e=>e.textContent.trim())")
    if not any('Weight & Body Composition' in t for t in titles): f.add('BUG', f'daily weight/body not merged: {titles}')
    if any('Sleep Detail' in t for t in titles) or any(t == 'Body Composition' for t in titles): f.add('BUG', f'look-alike daily sections still separate: {titles}')
    page.evaluate("mhTrendsGroupSet('food')")
    vis = page.evaluate("[...document.querySelectorAll('#trendsDailyView > .card-unit')].filter(e=>getComputedStyle(e).display!=='none').map(e=>e.id)")
    if any(v in ('dv-weight-wrap', 'dv-sleep-wrap', 'dv-activity-wrap') for v in vis): f.add('BUG', f'Food chip left body/heart sections in the daily view: {vis}')
    page.evaluate("mhTrendsGroupSet('body')")
    vis = page.evaluate("[...document.querySelectorAll('#trendsDailyView > .card-unit')].filter(e=>getComputedStyle(e).display!=='none').map(e=>e.id)")
    if vis != ['dv-weight-wrap']: f.add('BUG', f'Body chip in daily view should show only weight/body: {vis}')
    page.evaluate("mhTrendsGroupSet('patterns')")
    if page.evaluate("getComputedStyle(document.getElementById('mhDvPatternsHint')).display") == 'none': f.add('BUG', 'Patterns hint missing in single-day view')
    page.evaluate("mhTrendsGroupSet('all')")
    if errs: f.add('BUG', f'page errors {errs[:3]}')
    b.close()
print('findings', len(f)); sys.exit(1 if f else 0)
