"""Persona 51: charts follow the chosen weight unit (series stay kg), Compare Metrics gains fat / logged exercise / active calories, Journey has overlay chips whose choice persists."""
import sys, re; sys.path.insert(0, __file__.rsplit('/',1)[0])
from harness import *
from playwright.sync_api import sync_playwright
f = Findings()
with fresh_server() as root, sync_playwright() as pw:
    b = pw.chromium.launch(); errs = []
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, service_workers='block')
    ctx.route(re.compile(r'https://(cdn\.jsdelivr\.net|cdnjs\.cloudflare\.com|fonts\.(googleapis|gstatic)\.com)/.*'), lambda r: r.abort())
    page = ctx.new_page(); page.on('pageerror', lambda e: errs.append(str(e)[:160]))
    page.goto('http://localhost:5757/'); page.wait_for_timeout(1200)
    page.evaluate("localStorage.setItem('mh_weight_unit','lbs')")
    cv = page.evaluate("[mhChartCv('weight',90.7), mhChartCv('bone_mass',3.0), mhChartCv('hr',60), mhChartUnit('weight','kg'), mhChartUnit('hr','bpm'), mhChartCv('weight',null)]")
    if abs(cv[0]-200) > 0.2 or abs(cv[1]-6.6) > 0.1 or cv[2] != 60 or cv[3] != 'lb' or cv[4] != 'bpm' or cv[5] is not None:
        f.add('BUG', f'chart converters wrong in lbs: {cv}')
    page.evaluate("localStorage.setItem('mh_weight_unit','st')")
    if page.evaluate("mhChartUnit('weight','kg')") != 'lb': f.add('BUG', 'st charts should use lb axis')
    page.evaluate("localStorage.setItem('mh_weight_unit','kg')")
    if page.evaluate("mhChartCv('weight',90.7)") != 90.7 or page.evaluate("mhChartUnit('weight','kg')") != 'kg': f.add('BUG', 'kg charts changed')
    # data: exercise + active cal flow through getDrillData
    page.evaluate("""state.history = [
      {date:'01/10/26', weight:90, totals:{kcal:2000,protein:150,carbs:30,fat:150}, exercises:[{kcal:200},{kcal:150}], calories_active:640, water_ml:2000, steps:8000},
      {date:'02/10/26', weight:89.5, totals:{kcal:2100,protein:140,carbs:40,fat:140}, exercises:[], calories_active:500, water_ml:1500, steps:6000},
      {date:'03/10/26', weight:89.2, totals:{kcal:1900,protein:160,carbs:20,fat:120}, exercises:[{kcal:300}], water_ml:2500, steps:9000}];""")
    ex = page.evaluate("getDrillData('exercise_kcal',0).map(d=>d.val)")
    if ex != [350, 300]: f.add('BUG', f'exercise_kcal series wrong: {ex}')
    ac = page.evaluate("getDrillData('active_cal',0).map(d=>d.val)")
    if ac != [640, 500]: f.add('BUG', f'active_cal series wrong: {ac}')
    grp = page.evaluate("MM_METRIC_GROUPS.map(g=>[g.label, getAllOverlayableMetrics().filter(g.match).map(m=>m.key)])")
    d = dict((a, b2) for a, b2 in grp)
    if 'fat' not in d['Nutrition']: f.add('BUG', f"fat missing from Compare Metrics: {d['Nutrition']}")
    if 'exercise_kcal' not in d['Exercise'] or 'active_cal' not in d['Exercise']: f.add('BUG', f"exercise metrics missing: {d['Exercise']}")
    allkeys = [k for _, ks in grp for k in ks if not k.startswith(('symptom_', 'treatment_'))]
    base = page.evaluate("Object.keys(DRILL_CONFIG).filter(k=>!DRILL_CONFIG[k].isLabMarker)")
    miss = [k for k in base if k not in allkeys]
    if miss: f.add('BUG', f'metrics in no Compare group (invisible): {miss}')
    # journey chips
    page.evaluate("switchTabById('trends')"); page.wait_for_timeout(800)
    page.evaluate("renderJourneyCard()")
    n = page.evaluate("document.querySelectorAll('#journeyOverlayBar [data-jov]').length")
    if n != 7: f.add('BUG', f'expected 7 journey chips, got {n}')
    page.evaluate("mhJourneyToggleOverlay('exercise'); mhJourneyToggleOverlay('water')")
    if sorted(page.evaluate("mhJourneyOverlayKeys()")) != ['exercise', 'water']: f.add('BUG', 'overlay choice not saved')
    page.reload(); page.wait_for_timeout(1500)
    if sorted(page.evaluate("mhJourneyOverlayKeys()")) != ['exercise', 'water']: f.add('BUG', 'overlay choice lost on reload')
    page.evaluate("mhJourneyToggleOverlay('water')")
    if page.evaluate("mhJourneyOverlayKeys()") != ['exercise']: f.add('BUG', 'overlay untoggle failed')
    vals = page.evaluate("mhJourneyOverlayDefs().find(o=>o.key==='exercise').get({exercises:[{kcal:200},{kcal:150}]})")
    if vals != 350: f.add('BUG', f'journey exercise getter: {vals}')
    # day panel shows real overlay values
    page.evaluate("showJourneyDayPanel(0, [{date:'01/10/26', weight:90, exercises:[{kcal:200},{kcal:150}]}], ['#2deb8f'])")
    pt = page.evaluate("document.getElementById('journeyDayPanel').textContent")
    if '350' not in pt: f.add('BUG', f'journey day panel missing exercise value: {pt!r}')
    # v3.10.891: gap markers on the journey chart, backdated weight, copy previous set
    page.evaluate("localStorage.setItem('mh_weight_unit','lbs')")
    page.evaluate("""state.history=[
      {date:'01/09/26', weight:90, totals:{kcal:2000,protein:1,carbs:1,fat:1}},
      {date:'02/09/26', weight:89.8, totals:{kcal:2000,protein:1,carbs:1,fat:1}},
      {date:'20/09/26', weight:89.0, totals:{kcal:2000,protein:1,carbs:1,fat:1}}]""")
    page.evaluate("switchTabById('trends')"); page.wait_for_timeout(500); page.evaluate("renderJourneyCard()"); page.wait_for_timeout(800)
    ds = page.evaluate("(()=>{const c=chartInstances.journeyChart; return c?[c.data.labels,c.data.datasets[0].data,c.data.datasets[1].data]:null})()")
    if not ds or len(ds[0]) != 4 or ds[1][2] is not None or '18d' not in ds[0][2]: f.add('BUG', f'journey gap marker missing: {ds}')
    elif any(v is not None for v in ds[2]) and ds[2][2] is not None: f.add('BUG', 'treatment marker on gap')
    carry = page.evaluate("chartInstances.journeyChart.data.datasets.find(d=>d.label==='Last known').data")
    if not carry or carry[1] is None or carry[2] is None or carry[3] is None or carry[0] is not None: f.add('BUG', f'journey carry-forward wrong: {carry}')
    elif abs(carry[2] - carry[1]) > 0.01: f.add('BUG', f'carry not flat across gap: {carry}')
    cf = page.evaluate("mhCarryForward([90,null,null,89,null,88])")
    if cf != [90,90,90,89,89,89]: f.add('BUG', f'mhCarryForward: {cf}')
    if 'last known' not in page.evaluate("document.getElementById('journeyLegend').textContent"): f.add('BUG', 'legend missing last known')
    # backdated weight
    page.evaluate("localStorage.setItem('mh_weight_unit','kg'); state.weight=89.0; openWeightModal()")
    if not page.evaluate("document.getElementById('weightDateInput').value"): f.add('BUG', 'weight date picker empty')
    page.fill('#weightInput', '88.4'); page.evaluate("document.getElementById('weightDateInput').value='2026-09-10'"); page.evaluate("confirmWeight()")
    row = page.evaluate("state.history.find(h=>h.date==='10/09/26')")
    if not row or abs(row['weight'] - 88.4) > 0.01: f.add('BUG', f'backdated weight not saved: {row}')
    if abs(page.evaluate("state.weight") - 89.0) > 0.01: f.add('BUG', 'backdating moved current weight')
    page.evaluate("openWeightModal()"); page.fill('#weightInput', '91'); page.evaluate("document.getElementById('weightDateInput').value='2999-01-01'"); page.evaluate("confirmWeight()")
    if abs(page.evaluate("state.weight") - 89.0) > 0.01: f.add('BUG', 'future date accepted')
    page.evaluate("closeWeightModal()")
    # v3.10.893: add/fix a day's weight from the charts
    page.evaluate("state.history=[{date:'01/09/26',weight:90,totals:{kcal:1,protein:1,carbs:1,fat:1}},{date:'02/09/26',weight:89.8,totals:{kcal:1,protein:1,carbs:1,fat:1}},{date:'20/09/26',weight:89.0,totals:{kcal:1,protein:1,carbs:1,fat:1}}]")
    page.evaluate("openWeightModal('02/09/26')")
    if page.evaluate("document.getElementById('weightDateInput').value") != '2026-09-02' or page.evaluate("document.getElementById('weightInput').value") != '89.8': f.add('BUG', 'edit-a-day modal not prefilled with that day')
    page.evaluate("closeWeightModal(); openWeightModal('05/09/26')")
    if page.evaluate("document.getElementById('weightInput').value") != '' or page.evaluate("document.getElementById('weightDateInput').value") != '2026-09-05': f.add('BUG', 'missed-day modal should be empty on that date')
    page.evaluate("closeWeightModal()")
    page.evaluate("renderJourneyCard()"); page.wait_for_timeout(500)
    page.evaluate("showJourneyDayPanel(2, [{date:'01/09/26',weight:90},{date:'02/09/26',weight:89.8},{date:'⋯ 18d',_gap:true,_days:17,_firstMissing:'03/09/26'}], ['#fff','#fff','transparent'])")
    gp = page.evaluate("document.getElementById('journeyDayPanel').innerHTML")
    if "openWeightModal('03/09/26')" not in gp: f.add('BUG', 'gap panel missing add-weight link')
    page.evaluate("showJourneyDayPanel(0, [{date:'01/09/26',weight:90}], ['#fff'])")
    if "openWeightModal('01/09/26')" not in page.evaluate("document.getElementById('journeyDayPanel').innerHTML"): f.add('BUG', 'point panel missing edit link')
    md = page.evaluate("mhMissingWeightDate()")
    if not md or len(md.split('/')) != 3: f.add('BUG', f'mhMissingWeightDate: {md}')
    if page.evaluate("!!document.getElementById('mcWeightAddBtn')") is False: f.add('BUG', 'trends add button missing')
    # copy previous set (routine editor)
    page.evaluate("_routineDraftExercises=[{name:'Rowing',sets:[{reps:'10',weight_kg:40,note:'n'}]}]; _routineEditingId=null; document.body.insertAdjacentHTML('beforeend','<div id=routineExerciseRows></div>'); renderRoutineExerciseRows()")
    if page.evaluate("document.querySelectorAll('[data-copyprev]').length") != 1: f.add('BUG', 'copy previous link missing')
    page.evaluate("mhRoutineCopySet(0,0)"); page.evaluate("mhRoutineCopySet(0,1)")
    sets = page.evaluate("_routineDraftExercises[0].sets")
    if len(sets) != 3 or any(x['reps'] != '10' or x['weight_kg'] != 40 or x['note'] != 'n' for x in sets): f.add('BUG', f'copy set wrong: {sets}')
    page.evaluate("_routineDraftExercises[0].sets[2].reps='12'")
    if page.evaluate("_routineDraftExercises[0].sets[1].reps") != '10': f.add('BUG', 'copied set shares reference')
    page.evaluate("window._routineApplyDrafts=[{name:'Row',sets:[{reps:'8',weight_kg:'30',note:''}]}]; mhApplyCopyPrevSet(0)")
    if page.evaluate("window._routineApplyDrafts[0].sets.length") != 2: f.add('BUG', 'apply copy previous failed')
    if errs: f.add('BUG', f'page errors: {errs[:3]}')
    b.close()
print("findings", len(f)); sys.exit(1 if f else 0)
