"""Persona 53: photo ruler in Settings > Tableware: card-calibrated measurement lands in the item's Across (cm) box."""
import sys, re; sys.path.insert(0, __file__.rsplit('/',1)[0])
from harness import *
from playwright.sync_api import sync_playwright
f = Findings()
import tempfile, os
from PIL import Image, ImageDraw
# 1100x900: card long edge 342px = 85.6mm (4 px/mm); bowl 600px across = 15.0cm
IMG = os.path.join(tempfile.mkdtemp(), 'ruler.png')
_im = Image.new('RGB', (1100, 900), (120, 100, 80)); _d = ImageDraw.Draw(_im)
_d.rectangle([100, 100, 442, 316], fill=(30, 60, 160)); _d.ellipse([350, 200, 950, 800], fill=(240, 240, 240)); _im.save(IMG)
with fresh_server() as root, sync_playwright() as pw:
    b = pw.chromium.launch(); errs = []
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, service_workers='block')
    ctx.route(re.compile(r'https://(cdn\.jsdelivr\.net|cdnjs\.cloudflare\.com|fonts\.(googleapis|gstatic)\.com)/.*'), lambda r: r.abort())
    page = ctx.new_page(); page.on('pageerror', lambda e: errs.append(str(e)[:160]))
    page.goto('http://localhost:5757/'); page.wait_for_timeout(1500)
    page.evaluate("switchTabById('settings')"); page.wait_for_timeout(300); page.evaluate("mhRulerOpen('home','bowl')")
    if page.evaluate("document.querySelectorAll('#mhRulerModal input[type=file]:not([capture])').length") != 1 or page.evaluate("document.querySelectorAll('#mhRulerModal input[type=file][capture]').length") != 1: f.add('BUG', 'need one camera button and one gallery (no capture) button')
    page.evaluate("mhRulerClose()")
    # pure maths
    if page.evaluate("mhRulerCalc(342, 85.6, 600)") != 15.0: f.add('BUG', 'calc wrong')
    if page.evaluate("mhRulerCalc(0, 85.6, 600)") is not None or page.evaluate("mhRulerCalc(342, 0, 600)") is not None: f.add('BUG', 'calc accepted bad input')
    page.evaluate("switchTabById('settings')"); page.wait_for_timeout(500)
    page.evaluate("mhTwRender()")
    if page.evaluate("document.querySelectorAll('#mhTwCard [onclick^=\"mhRulerOpen\"]').length") != 6: f.add('BUG', '📏 should sit on plates, bowl and spoons (6), not on cups')
    page.evaluate("mhRulerOpen('home','bowl')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    def tap(x, y):
        box = page.evaluate("(()=>{const r=document.getElementById('mhRulerCanvas').getBoundingClientRect();return [r.left,r.top,r.width,r.height]})()")
        page.mouse.click(box[0] + x * box[2] / 1100, box[1] + y * box[3] / 900); page.wait_for_timeout(80)
    if 'Step 1 of 2' not in page.evaluate("document.getElementById('mhRulerBody').textContent"): f.add('BUG', 'no readable step hint before reference is set')
    if page.evaluate("[...document.querySelectorAll('#mhRulerBody button')].some(b => b.textContent.includes('Next') && getComputedStyle(b).opacity < 1)"): f.add('BUG', 'faded Next button')
    tap(100, 208); tap(442, 208)                    # card long edge
    page.evaluate("mhRulerNext()")
    tap(350, 500); tap(950, 500)                    # across the bowl
    txt = page.evaluate("document.getElementById('mhRulerBody').textContent")
    m = re.search(r'([\d.]+) cm across', txt)
    if not m or abs(float(m.group(1)) - 15.0) > 0.4: f.add('BUG', f'measured {m and m.group(1)} cm, expected ~15.0')
    page.evaluate("mhRulerUse()"); page.wait_for_timeout(300)
    v = page.evaluate("JSON.parse(localStorage.getItem('mh_tableware')).sets[0].vals.bowl")
    if not v or abs(v.get('diam', 0) - 15.0) > 0.4 or v.get('diam') == 15 and False: pass
    if page.evaluate("!!document.getElementById('mhRulerModal')"): f.add('BUG', 'modal stayed open after Use')
    # default bowl is 15 so equal-to-default removes the override; measure something different to prove the write
    page.evaluate("mhRulerOpen('home','dinner_plate')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    tap(100, 208); tap(442, 208); page.evaluate("mhRulerNext()"); tap(350, 500); tap(800, 500)
    page.evaluate("mhRulerUse()"); page.wait_for_timeout(300)
    d = page.evaluate("(JSON.parse(localStorage.getItem('mh_tableware')).sets[0].vals.dinner_plate||{}).diam")
    if not d or abs(d - 11.2) > 0.4: f.add('BUG', f'plate diam not saved from ruler: {d}')
    # v3.10.905 gestures: pinch zooms the photo (not the page), drag pans, neither places a point; Clear/Undo work
    page.evaluate("mhRulerOpen('home','mug')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    def ev(typ, pid, x, y):
        page.evaluate("""([t,id,x,y]) => { const v=document.getElementById('mhRulerView'); const r=v.getBoundingClientRect();
          v.dispatchEvent(new PointerEvent(t,{pointerId:id,pointerType:'touch',clientX:r.left+x,clientY:r.top+y,bubbles:true,isPrimary:id===1})); }""", [typ, pid, x, y])
    vw = page.evaluate("document.getElementById('mhRulerView').clientWidth")
    ev('pointerdown', 1, 150, 150); ev('pointerdown', 2, 200, 150)
    for i in range(1, 6): ev('pointermove', 1, 150 - i * 15, 150); ev('pointermove', 2, 200 + i * 15, 150)
    ev('pointerup', 1, 75, 150); ev('pointerup', 2, 275, 150)
    z = page.evaluate("document.getElementById('mhRulerCanvas').style.transform")
    m = re.search(r'scale\(([\d.]+)\)', z)
    if not m or float(m.group(1)) < 2: f.add('BUG', f'pinch did not zoom the photo: {z}')
    if page.evaluate("document.getElementById('mhRulerBody').textContent").count('2 to go') != 1 or page.evaluate("st_cal_len = 0") is None: pass
    if page.evaluate("window.visualViewport ? visualViewport.scale : 1") != 1: f.add('BUG', 'page itself got zoomed')
    ev('pointerdown', 1, 100, 100)
    for i in range(1, 6): ev('pointermove', 1, 100 + i * 10, 100 + i * 10)
    ev('pointerup', 1, 150, 150)
    if 'Step 1 of 2: tap both ends of the reference (2 to go)' not in page.evaluate("document.getElementById('mhRulerBody').textContent"): f.add('BUG', 'pinch/drag placed a stray point')
    page.evaluate("mhRulerZoom(3)"); tap(300, 300); tap(500, 300)
    if 'Reference set' not in page.evaluate("document.getElementById('mhRulerBody').textContent"): f.add('BUG', 'taps at zoom did not place the two points')
    page.evaluate("mhRulerUndo()")
    if '1 to go' not in page.evaluate("document.getElementById('mhRulerBody').textContent"): f.add('BUG', 'Undo did not remove the last point')
    page.evaluate("mhRulerReset()")
    if '2 to go' not in page.evaluate("document.getElementById('mhRulerBody').textContent"): f.add('BUG', 'Clear did not clear')
    page.evaluate("mhRulerClose()")
    # v3.10.906 nudge: place a point roughly, push it with the arrows, pick up the other point by tapping it
    page.evaluate("localStorage.setItem('mh_ruler_snap','0'); mhRulerOpen('home','mug')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    def pts(): return page.evaluate("(()=>{const t=document.getElementById('mhRulerBody').innerHTML; return 0})()")
    tap(100, 208)
    if not page.evaluate("document.getElementById('mhRulerNudge').style.display") == 'flex': f.add('BUG', 'nudge strip not shown after a point is placed')
    k = page.evaluate("(()=>{const c=document.getElementById('mhRulerCanvas'); return c.width/c.getBoundingClientRect().width})()")
    page.evaluate("mhRulerNudge(1,0)")
    for _ in range(9): page.evaluate("mhRulerNudge(1,0)")
    page.evaluate("mhRulerNudge(0,-1)")
    tap(442, 208)                                  # second point, becomes the picked one
    nud = page.evaluate("document.getElementById('mhRulerNudge').textContent")
    if 'Point 2 of 2' not in nud: f.add('BUG', f'second point not picked after placing: {nud[:60]}')
    tap(100 + 10 * k, 208 - k)                     # tap on the first point: picks it up, does not move anything
    if 'Point 1 of 2' not in page.evaluate("document.getElementById('mhRulerNudge').textContent"): f.add('BUG', 'tapping a point did not pick it up')
    page.evaluate("mhRulerNext()"); tap(350, 500); tap(950, 500)
    import math
    exp = 600 / math.hypot(442 - (100 + 10 * k), k) * 8.56   # first point moved 10 screen px right and 1 up
    txt = page.evaluate("document.getElementById('mhRulerBody').textContent")
    m = re.search(r'([\d.]+) cm across', txt)
    if not m or abs(float(m.group(1)) - exp) > 0.3: f.add('BUG', f'nudged measurement off: {m and m.group(1)} (expected ~{exp:.1f})')
    page.evaluate("mhRulerClose()")
    # v3.10.907 edge snap: taps a few pixels off the true edge land on it; flat areas are left alone; toggle works
    page.evaluate("localStorage.setItem('mh_ruler_snap','1'); mhRulerOpen('home','mug')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    tap(100 - 14, 208); tap(442 + 12, 208)         # card ends tapped ~13px outside the real edges (x=100 and x=442)
    page.evaluate("mhRulerNext()"); tap(350 - 11, 500); tap(950 + 9, 500)   # bowl edges (x=350 and x=950) tapped off
    m = re.search(r'([\d.]+) cm across', page.evaluate("document.getElementById('mhRulerBody').textContent"))
    if not m or abs(float(m.group(1)) - 15.0) > 0.35: f.add('BUG', f'snap did not land on the edges: {m and m.group(1)} cm (expected ~15.0)')
    page.evaluate("mhRulerClose()")
    page.evaluate("mhRulerOpen('home','mug')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    page.evaluate("mhRulerSnapToggle()")           # off
    tap(100 - 14, 208); tap(442 + 12, 208); page.evaluate("mhRulerNext()"); tap(350 - 11, 500); tap(950 + 9, 500)
    m2 = re.search(r'([\d.]+) cm across', page.evaluate("document.getElementById('mhRulerBody').textContent"))
    if not m2 or abs(float(m2.group(1)) - 15.0) < 0.35: f.add('BUG', 'snap-off should leave the taps exactly where they were (measurement should be visibly off)')
    page.evaluate("mhRulerSnapToggle(); mhRulerClose()")
    # flat area: no edge, point must not move
    page.evaluate("mhRulerOpen('home','mug')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    moved = page.evaluate("mhRulerSnapPoint({x:900,y:150},{x:1000,y:150},2)")
    if abs(moved['x'] - 900) > 0.01 or abs(moved['y'] - 150) > 0.01: f.add('BUG', f'snap moved a point with no edge nearby: {moved}')
    page.evaluate("mhRulerClose()")
    # a smaller card: type its length and it is remembered
    page.evaluate("mhRulerOpen('home','mug')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    page.evaluate("mhRulerRef('custom'); mhRulerCustom('64')")
    page.evaluate("mhRulerClose(); mhRulerOpen('home','mug')")
    if page.evaluate("JSON.parse(localStorage.getItem('mh_ruler_ref')).customMm") != 64: f.add('BUG', 'typed reference length not remembered')
    page.evaluate("mhRulerClose()")
    # absurd result is refused
    page.evaluate("localStorage.removeItem('mh_ruler_ref'); mhRulerOpen('home','dinner_plate')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    tap(100, 208); tap(110, 208); page.evaluate("mhRulerNext()"); tap(100, 500); tap(1000, 500); page.evaluate("mhRulerUse()")
    if not page.evaluate("!!document.getElementById('mhRulerModal')"): f.add('BUG', 'absurd measurement (>60cm) was accepted')
    page.evaluate("mhRulerClose()")
    # v3.10.909 food area: third point is one tap on the inner rim edge, measured from the plate centre
    page.evaluate("localStorage.removeItem('mh_ruler_ref'); localStorage.setItem('mh_ruler_snap','0'); mhRulerOpen('home','mug')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    tap(100, 208); tap(442, 208); page.evaluate("mhRulerNext()"); tap(350, 500); tap(950, 500)
    if 'Food area' in page.evaluate("document.getElementById('mhRulerBar').textContent"): f.add('BUG', 'a mug should not offer a food-area step')
    page.evaluate("mhRulerClose()")
    page.evaluate("mhRulerOpen('home','dinner_plate')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    if 'Step 1 of 3' not in page.evaluate("document.getElementById('mhRulerBody').textContent"): f.add('BUG', 'plate should be a 3-step measurement')
    tap(100, 208); tap(442, 208); page.evaluate("mhRulerNext()"); tap(350, 500); tap(950, 500)
    if 'Food area' not in page.evaluate("document.getElementById('mhRulerBar').textContent"): f.add('BUG', 'plate has no Food area button after the width')
    page.evaluate("mhRulerNext()")
    if 'Step 3 of 3' not in page.evaluate("document.getElementById('mhRulerBar').textContent"): f.add('BUG', 'no third step hint')
    tap(850, 500)                                   # 200px from the centre (650,500) = 400px across = 10.0 cm
    bar = page.evaluate("document.getElementById('mhRulerBar').textContent")
    mf = re.search(r'([\d.]+) cm food area', bar)
    if not mf or abs(float(mf.group(1)) - 10.0) > 0.3: f.add('BUG', f'food area {mf and mf.group(1)}, expected ~10.0')
    page.evaluate("mhRulerUse(true)"); page.wait_for_timeout(300)
    v = page.evaluate("JSON.parse(localStorage.getItem('mh_tableware')).sets[0].vals.dinner_plate")
    if not v or abs(v.get('food', 0) - 10.0) > 0.3 or abs(v.get('diam', 0) - 15.0) > 0.4: f.add('BUG', f'width + food area not both saved: {v}')
    if 'food area (inside the rim) about' not in page.evaluate("mhTablewareLine()"): f.add('BUG', 'food area not in the AI line')
    # a food area bigger than the plate is refused
    page.evaluate("mhRulerOpen('home','dinner_plate')")
    page.set_input_files('#mhRulerModal input[type=file]:not([capture])', IMG); page.wait_for_selector('#mhRulerCanvas', timeout=5000)
    tap(100, 208); tap(442, 208); page.evaluate("mhRulerNext()"); tap(350, 500); tap(950, 500); page.evaluate("mhRulerNext()"); tap(1050, 500)
    page.evaluate("mhRulerUse(true)")
    if not page.evaluate("!!document.getElementById('mhRulerModal')"): f.add('BUG', 'food area larger than the plate was accepted')
    page.evaluate("mhRulerBack()")
    if 'across' not in page.evaluate("document.getElementById('mhRulerBar').textContent"): f.add('BUG', 'Back from food step did not return to the width step')
    page.evaluate("mhRulerClose()")
    page.evaluate("localStorage.setItem('mh_ruler_snap','1')")
    if errs: f.add('BUG', f'page errors: {errs[:3]}')
    b.close()
print("findings", len(f)); sys.exit(1 if f else 0)
